spring:
  application:
    name: reference-data-api
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      group-id: my-consumer-group
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

topics:
  trades: trades-topic
  enriched-trades: enriched-trades-topic
  isin: isin-topic

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG
